name: Parse and Comment back on issue
on:
  issues:
    types: ['opened']
  issue_comment:
    types: ['created']

jobs:
  parse-issue:
    if: github.event_name != 'push' && github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    name: Parse issue, scan and comment back for non-inclusive language
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          check-latest: true
      - name: parsing from body of the issue
        uses: ./
        id: parseissue
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: non-inclusive